services:
  - type: web
    name: yashoda-bhavan-hms
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: GMAIL_REDIRECT_URI
        value: https://developers.google.com/oauthplayground
      - key: CLIENT_URL
        fromService:
          name: yashoda-bhavan-hms
          type: web
          property: host
