const dotenv = require('dotenv');
dotenv.config();
const { sequelize } = require('./config/db');

async function fixIndexes() {
    try {
        await sequelize.authenticate();
        console.log('Connected to DB');

        const [results] = await sequelize.query("SHOW INDEX FROM Users");
        const indexes = results;

        // Group indexes by key name
        const indexGroups = {};
        indexes.forEach(idx => {
            if (idx.Key_name === 'PRIMARY') return;
            if (!indexGroups[idx.Key_name]) {
                indexGroups[idx.Key_name] = [];
            }
            indexGroups[idx.Key_name].push(idx);
        });

        console.log(`Found ${Object.keys(indexGroups).length} unique index names (excluding PRIMARY).`);
        console.log(`Total indexes found: ${indexes.length}`);

        const droppedIndexes = [];

        // Logic: Identify duplicates based on pattern (e.g., nameHash, nameHash_1, nameHash_2)
        // Ideally, we keep the clean name and drop the numbered ones.
        for (const keyName of Object.keys(indexGroups)) {
            // Simple heuristic: if it ends in _\d+, it's likely a duplicate auto-generated by Sequelize
            if (keyName.match(/_\d+$/)) {
                try {
                    console.log(`Dropping index: ${keyName}`);
                    await sequelize.query(`DROP INDEX \`${keyName}\` ON Users`);
                    droppedIndexes.push(keyName);
                } catch (err) {
                    console.error(`Failed to drop ${keyName}:`, err.message);
                }
            }
        }

        console.log(`Dropped ${droppedIndexes.length} indexes.`);
        process.exit(0);

    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
}

fixIndexes();
